# Generated by Django 6.1.1 on 2026-09-25 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('website', models.URLField(blank=True)),
                ('content_access', models.CharField(choices=[('all', 'All Ages only'), ('teen', 'Up to 13+'), ('mature', 'Full Access')], default='mature', max_length=10)),
                ('fear_moods', models.CharField(blank=True, max_length=100)),
                ('reading_speed', models.CharField(choices=[('slow', 'Slow'), ('average', 'Average'), ('fast', 'Fast')], default='average', max_length=10)),
                ('weekly_digest', models.BooleanField(default=True)),
                ('comment_digest', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('never', 'Never')], default='weekly', max_length=10)),
                ('profile_theme', models.CharField(choices=[('blood-red', 'Blood Red'), ('ghost-blue', 'Ghost Blue'), ('void', 'Void'), ('crimson', 'Crimson'), ('shadow', 'Shadow'), ('toxic', 'Toxic')], default='blood-red', max_length=20)),
                ('avatar_border', models.CharField(choices=[('none', 'None'), ('pulse', 'Pulse Glow'), ('orbit', 'Orbit Ring'), ('flicker', 'Flicker')], default='none', max_length=20)),
                ('is_private', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('blocker', 'blocked')},
            },
        ),
    ]
