# Generated by Django 6.1.1 on 2026-09-26 08:41

from django.db import migrations, models


# A "data migration": besides adding the new columns, fill them in
# for the people who already exist. Everyone who has written a story
# becomes an 'author' (new users get that automatically when they
# write their first one).
#
# apps.get_model(...) instead of importing the models: a migration
# must use the models as they were AT THIS POINT in history, not as
# they look in models.py today.
def mark_existing_authors(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('accounts', 'Profile')

    for user in User.objects.filter(stories__isnull=False).distinct():
        profile, _ = Profile.objects.get_or_create(user=user)
        profile.role = 'author'
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_block'),
        # We look at stories below, so their table must exist first.
        ('stories', '0006_coauthorinvite_readinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('author', 'Author')], default='user', max_length=10),
        ),
        # RunPython runs our function. The second one (noop) is what
        # to do when the migration is undone: nothing.
        migrations.RunPython(mark_existing_authors, migrations.RunPython.noop),
    ]
