# Generated by Django 6.1.1 on 2026-09-27 14:43

from django.conf import settings
from django.db import migrations


# A "data migration": it changes ROWS, not the table's shape.
#
# Email checking is new. The accounts that already exist signed up
# before there was anything to click - so we count them as confirmed
# (otherwise they'd suddenly stop getting their newsletter).
# New sign-ups start as False and must click the link.
#
# apps.get_model(...) instead of importing the model: a migration
# must use the model AS IT WAS at this point in history.
def mark_existing_verified(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    Profile = apps.get_model('accounts', 'Profile')
    for user in User.objects.all():
        Profile.objects.update_or_create(user=user, defaults={'email_verified': True})


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_email_verified'),
    ]

    operations = [
        # The second function runs when you UNDO the migration - here,
        # nothing needs undoing.
        migrations.RunPython(mark_existing_verified, migrations.RunPython.noop),
    ]
