# Generated by Django 6.1.1 on 2026-09-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_existing_accounts_are_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('invite', 'Co-author invite'), ('support', 'Support reply'), ('reply', 'Comment reply')], max_length=10),
        ),
    ]
