# Generated by Django 6.1.1 on 2026-09-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_notification_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notify_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_follows',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_likes',
            field=models.BooleanField(default=True),
        ),
    ]
