# Generated by Django 6.1.1 on 2026-09-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_more_notification_kinds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('invite', 'Co-author invite'), ('support', 'Support reply'), ('reply', 'Comment reply'), ('forum', 'Forum reply'), ('chain', 'Story chain'), ('beta', 'Beta reading'), ('truestory', 'True story review')], max_length=10),
        ),
    ]
