# Generated by Django 6.1.1 on 2026-09-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_notification_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tip_url',
            field=models.URLField(blank=True),
        ),
    ]
