# Generated by Django 6.1.1 on 2026-09-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_notification_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follow_digest',
            field=models.BooleanField(default=True),
        ),
    ]
