# Generated by Django 6.1.1 on 2026-10-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_profile_follow_digest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('invite', 'Co-author invite'), ('support', 'Support reply'), ('reply', 'Comment reply'), ('forum', 'Forum reply'), ('chain', 'Story chain'), ('beta', 'Beta reading'), ('truestory', 'True story review'), ('challenge', 'Challenge results'), ('tip', 'Tip (a candle)')], max_length=10),
        ),
    ]
