# Generated by Django 6.1.1 on 2026-10-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_notification_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name_color',
            field=models.CharField(blank=True, choices=[('', 'Normal'), ('blood', 'Blood red'), ('ember', 'Ember'), ('toxic', 'Toxic green'), ('void', 'Void purple'), ('ghost', 'Ghost blue')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_border',
            field=models.CharField(choices=[('none', 'None'), ('pulse', 'Pulse Glow'), ('orbit', 'Orbit Ring'), ('flicker', 'Flicker'), ('gold', 'Gold Crown (Pro)')], default='none', max_length=20),
        ),
    ]
