# Generated by Django 6.1.1 on 2026-09-27 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_bannedword_ban_userwarning_verificationrequest'),
        ('stories', '0009_tag_story_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToxicityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('category', models.CharField(max_length=20)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('clean', 'Looks fine'), ('flagged', 'Waiting for review'), ('hidden', 'Hidden by an admin'), ('approved', 'Approved by an admin')], max_length=10)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='toxicity', to='stories.comment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', '-checked_at'],
            },
        ),
    ]
