# Generated by Django 6.1.1 on 2026-09-28 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0003_toxicitycheck'),
        ('stories', '0026_readalongmessage_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='chat_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='stories.readalongmessage'),
        ),
        migrations.AddField(
            model_name='report',
            name='reading_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='stories.readinglist'),
        ),
    ]
