# Generated by Django 6.1.1 on 2026-09-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0002_cookiebanner_cookieconsent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodOfDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('mood', models.CharField(choices=[('creepy', 'Creepy'), ('sad', 'Sad'), ('mysterious', 'Mysterious'), ('terrifying', 'Terrifying'), ('unsettling', 'Unsettling'), ('shocking', 'Shocking')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
