# Generated by Django 6.1.1 on 2026-09-28 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0004_poll_featuredauthor_polloption_spotlight_pollvote'),
        ('stories', '0011_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('youtube_id', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='stories.story')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
