# Generated by Django 6.1.1 on 2026-09-28 09:36

import django.db.models.deletion
import sitecontent.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0005_video'),
        ('stories', '0016_reading_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VillainNomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('week', models.DateField(default=sitecontent.models.week_start)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nominated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villain_nominations', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='villain_nominations', to='stories.story')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('nominated_by', 'week')},
            },
        ),
        migrations.CreateModel(
            name='VillainVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField(default=sitecontent.models.week_start)),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='sitecontent.villainnomination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villain_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'week')},
            },
        ),
    ]
