# Generated by Django 6.1.1 on 2026-09-28 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0006_villain_of_the_week'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeJudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judges', to='sitecontent.challenge')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judging', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('challenge', 'judge')},
            },
        ),
        migrations.CreateModel(
            name='JudgeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('note', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='sitecontent.challengeentry')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('entry', 'judge')},
            },
        ),
    ]
