# Generated by Django 6.1.1 on 2026-09-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('general', 'General question'), ('report', 'Report a story or comment'), ('bug', 'Something is broken'), ('account', 'Help with my account'), ('partnership', 'Partnership / press'), ('other', 'Something else')], max_length=20)),
                ('message', models.TextField(max_length=5000)),
                ('is_handled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
