# Generated by Django 6.1.1 on 2026-09-27 10:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.CharField(default="We're doing some work on the site. Back soon!", max_length=300)),
                ('signups_open', models.BooleanField(default=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('login_max_per_username', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('login_max_per_ip', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('login_lock_minutes', models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)])),
                ('contact_per_hour', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('comments_per_hour', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('messages_per_hour', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('action', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=300)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
