# Generated by Django 6.1.1 on 2026-09-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='allow_indexing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_description',
            field=models.CharField(default='A community for horror story readers and writers.', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_title',
            field=models.CharField(default='Silent Evidence', max_length=70),
        ),
    ]
