# Generated by Django 6.1.1 on 2026-09-27 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_sitesettings_allow_indexing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('frontend', 'Browser (React)'), ('backend', 'Server (Django)')], max_length=10)),
                ('message', models.CharField(max_length=300)),
                ('details', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('count', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
    ]
