# Generated by Django 6.1.1 on 2026-09-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_comment_bookmark_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='audio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='story',
            name='content_rating',
            field=models.CharField(choices=[('all', 'All Ages'), ('teen', '13+ Teen'), ('mature', '18+ Mature')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='story',
            name='content_warnings',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='story',
            name='cover_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='story',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='story',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='story',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='mood',
            field=models.CharField(blank=True, choices=[('creepy', 'Creepy'), ('sad', 'Sad'), ('mysterious', 'Mysterious'), ('terrifying', 'Terrifying'), ('unsettling', 'Unsettling'), ('shocking', 'Shocking')], max_length=20),
        ),
        migrations.AddField(
            model_name='story',
            name='publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
