# Generated by Django 6.1.1 on 2026-09-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_coauthorinvite_readinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
