# Generated by Django 6.1.1 on 2026-09-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_story_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lastword',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
