# Generated by Django 6.1.1 on 2026-09-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0015_beta_readers'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinghistory',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
