# Generated by Django 6.1.1 on 2026-09-28 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0017_writing_sprints'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryViewDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_days', to='stories.story')),
            ],
            options={
                'unique_together': {('story', 'date')},
            },
        ),
    ]
