# Generated by Django 6.1.1 on 2026-09-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0020_reading_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='audio/'),
        ),
    ]
