# Generated by Django 6.1.1 on 2026-09-28 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0021_story_audio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField()),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='stories.story')),
            ],
            options={
                'ordering': ['-saved_at', '-id'],
            },
        ),
    ]
