# Generated by Django 6.1.1 on 2026-09-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0022_story_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='truestorysubmission',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='truestorysubmission',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
