# Generated by Django 6.1.1 on 2026-09-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0025_writing_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='readalongmessage',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
