# Generated by Django 6.1.1 on 2026-10-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0027_search_trigram_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='early_access_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
